-- Tạo database với bảng mã hỗ trợ tiếng Việt đầy đủ
CREATE DATABASE IF NOT EXISTS qldiem CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE qldiem;

-- 1. Bảng Khoa
CREATE TABLE KHOA (
    MaKhoa VARCHAR(10) PRIMARY KEY,
    TenKhoa VARCHAR(100) NOT NULL,
    NgayThanhLap DATE,
    TruongKhoa VARCHAR(100)
);

-- 2. Bảng Ngành
CREATE TABLE NGANH (
    MaNganh VARCHAR(10) PRIMARY KEY,
    TenNganh VARCHAR(100) NOT NULL,
    MaKhoa VARCHAR(10) NOT NULL,
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
);

-- 3. Bảng Giảng Viên
CREATE TABLE GIANG_VIEN (
    MaGiangVien VARCHAR(20) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh VARCHAR(10),
    Email VARCHAR(100),
    SoDienThoai VARCHAR(15),
    HocVi VARCHAR(50),
    MaKhoa VARCHAR(10) NOT NULL,
    TrangThai BIT DEFAULT 1,
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
);

-- 4. Bảng Lớp Hành Chính
CREATE TABLE LOP_HANH_CHINH (
    MaLop VARCHAR(20) PRIMARY KEY,
    TenLop VARCHAR(100) NOT NULL,
    MaNganh VARCHAR(10) NOT NULL,
    KhoaHoc INT,
    MaCoVan VARCHAR(20),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh),
    FOREIGN KEY (MaCoVan) REFERENCES GIANG_VIEN(MaGiangVien)
);

-- 5. Bảng Sinh Viên
CREATE TABLE SINH_VIEN (
    MaSinhVien VARCHAR(20) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh VARCHAR(10),
    DiaChi VARCHAR(255),
    Email VARCHAR(100),
    SoDienThoai VARCHAR(15),
    MaLop VARCHAR(20) NOT NULL,
    TrangThaiHocTap VARCHAR(50) DEFAULT 'Đang học',
    FOREIGN KEY (MaLop) REFERENCES LOP_HANH_CHINH(MaLop)
);

-- 6. Bảng Môn Học
CREATE TABLE MON_HOC (
    MaMonHoc VARCHAR(20) PRIMARY KEY,
    TenMonHoc VARCHAR(100) NOT NULL,
    SoTinChi INT NOT NULL CHECK (SoTinChi > 0),
    SoTietLyThuyet INT DEFAULT 0,
    SoTietThucHanh INT DEFAULT 0,
    MaNganh VARCHAR(10),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
);

-- 7. Bảng Học Kỳ
CREATE TABLE HOC_KY (
    MaHocKy VARCHAR(10) PRIMARY KEY,
    TenHocKy VARCHAR(50),
    NamHoc INT,
    NgayBatDau DATE,
    NgayKetThuc DATE
);

-- 8. Bảng Lớp Học Phần
CREATE TABLE LOP_HOC_PHAN (
    MaLopHocPhan VARCHAR(20) PRIMARY KEY,
    MaMonHoc VARCHAR(20) NOT NULL,
    MaHocKy VARCHAR(10) NOT NULL,
    MaGiangVien VARCHAR(20) NOT NULL,
    PhongHoc VARCHAR(50),
    SoLuongToiDa INT DEFAULT 60,
    TrangThai INT DEFAULT 1,
    FOREIGN KEY (MaMonHoc) REFERENCES MON_HOC(MaMonHoc),
    FOREIGN KEY (MaHocKy) REFERENCES HOC_KY(MaHocKy),
    FOREIGN KEY (MaGiangVien) REFERENCES GIANG_VIEN(MaGiangVien)
);

-- 9. Bảng Loại Điểm
CREATE TABLE LOAI_DIEM (
    MaLoaiDiem VARCHAR(10) PRIMARY KEY,
    TenLoaiDiem VARCHAR(50) NOT NULL
);

-- 10. Bảng Cấu Trúc Điểm
-- Thay IDENTITY bằng AUTO_INCREMENT
CREATE TABLE CAU_TRUC_DIEM (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    MaMonHoc VARCHAR(20) NOT NULL,
    MaLoaiDiem VARCHAR(10) NOT NULL,
    HeSo FLOAT NOT NULL CHECK (HeSo > 0 AND HeSo <= 1),
    MoTa VARCHAR(100),
    FOREIGN KEY (MaMonHoc) REFERENCES MON_HOC(MaMonHoc),
    FOREIGN KEY (MaLoaiDiem) REFERENCES LOAI_DIEM(MaLoaiDiem)
);

-- 11. Bảng Đăng Ký Học
-- Thay IDENTITY bằng AUTO_INCREMENT và GETDATE() bằng CURRENT_TIMESTAMP
CREATE TABLE DANG_KY_HOC (
    MaDangKy INT AUTO_INCREMENT PRIMARY KEY,
    MaSinhVien VARCHAR(20) NOT NULL,
    MaLopHocPhan VARCHAR(20) NOT NULL,
    NgayDangKy DATETIME DEFAULT CURRENT_TIMESTAMP,
    DiemTongKet FLOAT,
    DiemChu VARCHAR(2),
    DiemSo FLOAT,
    KetQua BIT,
    FOREIGN KEY (MaSinhVien) REFERENCES SINH_VIEN(MaSinhVien),
    FOREIGN KEY (MaLopHocPhan) REFERENCES LOP_HOC_PHAN(MaLopHocPhan),
    CONSTRAINT UQ_SinhVien_Lop UNIQUE (MaSinhVien, MaLopHocPhan)
);

-- 12. Bảng Chi Tiết Điểm
CREATE TABLE CHI_TIET_DIEM (
    MaChiTiet INT AUTO_INCREMENT PRIMARY KEY,
    MaDangKy INT NOT NULL,
    MaLoaiDiem VARCHAR(10) NOT NULL,
    SoDiem DECIMAL(4, 2) CHECK (SoDiem >= 0 AND SoDiem <= 10),
    NgayNhap DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiNhap VARCHAR(20),
    FOREIGN KEY (MaDangKy) REFERENCES DANG_KY_HOC(MaDangKy),
    FOREIGN KEY (MaLoaiDiem) REFERENCES LOAI_DIEM(MaLoaiDiem)
);

-- 13. Bảng User
-- Tên bảng USER phải đặt trong dấu ` ` vì trùng từ khóa hệ thống của MySQL
CREATE TABLE `USER` (
    MaUser INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    SoDienThoai VARCHAR(15),
    VaiTro VARCHAR(50) NOT NULL,
    TrangThai BIT DEFAULT 1,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);